openapi: 3.0.0
info:
  title: URL Shortener
  version: 1.0.0
paths:
  /:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: название бакета !!!
        object: название html-файла !!!
        presigned_redirect: false
        service_account_id: id сервисного аккаунта !!!
      operationId: static
